name: PlatformIO CI

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: write
  pull-requests: write

jobs:
  # CI では native (PC) を対象としたテストを行う。
  # Arduino.h や M5Unified.h などが必要なテストは実機環境が必要なので、CI ではテストしない（できない）。
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0

    - name: Set up Python
      uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
      with:
        python-version-file: '.python-version'

    - name: Install PlatformIO
      run: pip install platformio

    - name: Run PlatformIO native test
      run: pio test -e native

  # 対応する機種ごとにファームウェアをビルドする。
  # 機種を追加したら environment に追記すること。
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        environment:
          - M5Paper
          - M5PaperS3
          - M5PaperColor
          - M5PaperMono

    steps:
    - name: Checkout repository
      uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0

    - name: Set up Python
      uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
      with:
        python-version-file: '.python-version'

    - name: Install PlatformIO
      run: pip install platformio

    - name: Run PlatformIO build
      run: pio run -e ${{ matrix.environment }}

    - name: Upload bin-file as artifacts
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
      with:
        name: firmware-${{ matrix.environment }}
        path: .pio/build/${{ matrix.environment }}/**/*.bin
        if-no-files-found: error

  # 全機種のビルドが揃ってから 1 件だけコメントする
  comment:
    runs-on: ubuntu-latest
    needs: [test, build]
    steps:
    - name: Create or Update PR Comment
      uses: peter-evans/create-or-update-comment@71345be0265236311c031f5c7866368bd1eff043 # v4.0.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        repository: ${{ github.repository }}
        issue-number: ${{ github.event.pull_request.number }}
        body: |
          :rocket: 全機種のビルドが成功しました

          M5Paper / M5PaperS3 / M5PaperColor / M5PaperMono

          [こちらからダウンロードできます](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}#artifacts)
